### ISSUE TITLE
Upload error on macos

### ISSUE THREAD

**Issue by guigur** [owntech-foundation/bootloader#1]
I got the following error on macos:
```*** [upload] ./owntech/third_party/mcumgr-mac: Permission denied```

I've navigated to the folder `owntech/third_party` and executed this command on a terminal:
```$ chmod +x mcumgr-mac```

This command will allow the mcumgr to execute properly.

**Comment by jalinei** [comment]
In `owntech/scripts/helper_functions.py` 

```    if make_exec:
        if platform.system() == 'Linux':
            # Make file executable
            st = os.stat(file_path)
            os.chmod(file_path, st.st_mode | S_IXUSR | S_IXGRP | S_IXOTH)
```

Seems easy to fix.

**Comment by jalinei** [comment]
https://gitlab.laas.fr/owntech/power-api/core/-/commit/bcabc171ae2af575af11e6f522f35e10773d336f

Should be fixed by commit above.

**Comment by guigur** [comment]
working on version [bcabc17](https://github.com/owntech-foundation/Core/commit/bcabc171ae2af575af11e6f522f35e10773d336f)
Thanks
